version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0
jobs:
  sonar-scan:
    working_directory: ~/project/bezkoder-app
    steps:
      - checkout
      - run:
          name: SonarQube Scan
          command: sonar-scanner
